### ISSUE TITLE
only the trans flag works

### ISSUE THREAD

**Issue by 13-05** [GeopJr/BLAHAJ#1]
it seems like only the trans flag works. image:
![image](https://user-images.githubusercontent.com/64506392/209409600-2faac345-28f2-44fa-9f98-d726fe3a1dce.png)

**Comment by GeopJr** [comment]
Oops, I messed up the flags in the examples...

It should be `-c <flag>`: `blahaj -f -c lesbian`

Thanks for raising this issue, I'll fix it asap!
